name: Mypy
on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install --upgrade pip
    - run: pip install mypy==1.5.1
    - run: yes | mypy --install-types --config-file pyproject.toml optexp || true
    - run: mypy --config-file pyproject.toml --ignore-missing-imports optexp
